In [6]:
import numpy as np
letters=np.array(["a","b","c","d","e","f","g","h","i","j"])
print(letters.shape)
print(letters.size)
print(letters.dtype)

(10,)
10
<U1


In [7]:
import numpy as np
y = np.arange(2,34,2).reshape(4,4)
print(y)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [12]:
import numpy as np
z=np.linspace(2,32,16).reshape(4,4)
print(z)

[[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]
 [18. 20. 22. 24.]
 [26. 28. 30. 32.]]


In [19]:
import numpy as np
A = np.arange(1, 26).reshape(5, 5)
odd =A[A % 2 == 1]
print(A)
print(odd)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
